[package]
name = "pty"
version = "0.1.0"
edition = "2021"

[dependencies]
tmui = { git = "https://github.com/toocol/tmui" }
termio = { git = "https://github.com/toocol/termio" }

ipc = { path = "../ipc" }
