[package]
name = "builtin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }

ipc = { path = "../ipc" }

ahash = "0.8.11"
