[package]
name = "ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
tmui = { git = "https://github.com/toocol/tmui" }
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }

log = "0.4"
